#!/usr/bin/env bash
#
# rserve-proxy installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/tmelliott/rserve-proxy/main/install.sh | bash
#
# What it does:
#   1. Checks for Docker + Docker Compose
#   2. Clones the repo (or pulls updates if already cloned)
#   3. Generates a .env with random secrets
#   4. Builds and starts the stack
#   5. The app auto-migrates the database and seeds the admin user on first boot
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

REPO_URL="${RSERVE_REPO:-https://github.com/tmelliott/rserve-proxy.git}"
INSTALL_DIR="${RSERVE_DIR:-$HOME/rserve-proxy}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

info()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()    { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m==>\033[0m %s\n' "$*"; }
error() { printf '\033[1;31m==>\033[0m %s\n' "$*" >&2; }

random_secret() {
  openssl rand -base64 32 | tr -d '/+=' | head -c 40
}

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  error "Docker is not installed."
  echo "  Install it from https://docs.docker.com/engine/install/"
  echo "  Or run:  curl -fsSL https://get.docker.com | sh"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 is not available."
  echo "  It should be included with Docker Desktop or the docker-compose-plugin package."
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  error "Docker daemon is not running, or you don't have permission."
  echo "  Try: sudo systemctl start docker"
  echo "  Or add your user to the docker group: sudo usermod -aG docker \$USER"
  exit 1
fi

ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+') + Compose available"

# ---------------------------------------------------------------------------
# Clone or update the repo
# ---------------------------------------------------------------------------

if [ -d "$INSTALL_DIR/.git" ]; then
  info "Updating existing install at $INSTALL_DIR..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Cloning rserve-proxy to $INSTALL_DIR..."
  git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ---------------------------------------------------------------------------
# Generate .env (only if it doesn't exist)
# ---------------------------------------------------------------------------

if [ ! -f .env ]; then
  info "Generating .env with random secrets..."

  DB_PASSWORD=$(random_secret)
  SESSION_SECRET=$(random_secret)
  ADMIN_PASSWORD=$(random_secret)

  echo -n "Enter the domain for this instance (or leave blank for localhost): "
  read -r DOMAIN
  DOMAIN="${DOMAIN:-localhost}"

  cat > .env <<EOF
# Auto-generated by install.sh — $(date -Iseconds)
DB_PASSWORD=$DB_PASSWORD
SESSION_SECRET=$SESSION_SECRET
ADMIN_PASSWORD=$ADMIN_PASSWORD
DOMAIN=$DOMAIN
EOF

  ok "Created .env"
  echo ""
  echo "  Admin credentials:"
  echo "    Username: admin"
  echo "    Password: $ADMIN_PASSWORD"
  echo ""
  warn "Save the admin password above — it won't be shown again."
  echo ""
else
  ok ".env already exists — keeping existing secrets"
fi

# ---------------------------------------------------------------------------
# Build rserve-base image
# ---------------------------------------------------------------------------

info "Building rserve-base image (needed by app spawner)..."
bash images/rserve-base/build.sh

# ---------------------------------------------------------------------------
# Build and start
# ---------------------------------------------------------------------------

info "Building and starting the stack (this may take a few minutes on first run)..."

docker compose up -d --build --remove-orphans

# ---------------------------------------------------------------------------
# Wait for healthy
# ---------------------------------------------------------------------------

info "Waiting for services to be ready..."

TRIES=0
MAX_TRIES=30
until docker compose ps --format json | grep -q '"Health":"healthy"' 2>/dev/null || \
      docker compose ps | grep -q "(healthy)" 2>/dev/null; do
  TRIES=$((TRIES + 1))
  if [ "$TRIES" -ge "$MAX_TRIES" ]; then
    warn "Timed out waiting for services. Check: docker compose logs"
    break
  fi
  sleep 2
done

# Give the manager a moment to run migrations and seed
sleep 3

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
ok "rserve-proxy is running!"
echo ""
echo "  Dashboard:  http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost')"
echo "  Admin user: admin"
if [ -f .env ]; then
  ADMIN_PW=$(grep ADMIN_PASSWORD .env | cut -d= -f2)
  if [ -n "$ADMIN_PW" ] && [ "$ADMIN_PW" != "admin" ]; then
    echo "  Password:   (see .env file)"
  else
    echo "  Password:   admin"
  fi
fi
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f       # Follow logs"
echo "    docker compose down           # Stop"
echo "    docker compose up -d --build  # Rebuild after updates"
echo ""
